on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - uses: frabert/replace-string-action@v1.2
        id: CleanChangelog
        with:
          pattern: '0.0.0-dev '
          string: |
            ${{ steps.Changelog.outputs.changelog }}
          replace-with: ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.CleanChangelog.outputs.replaced }}
          draft: false
          prerelease: false
